### ISSUE TITLE
Offer downstream peribolos changes to upstream

### ISSUE THREAD

**Issue by tumido** [operate-first/peribolos-as-a-service#150]
**Is your feature request related to a problem? Please describe.**
We want to be good members of the open source community, so we should make our downstream changes to peribolos available upstream.

**Describe the solution you'd like**
Offer all changes present in https://github.com/open-services-group/peribolos-as-a-service/blob/main/peribolos-fix/peribolos.patch as a PR to https://github.com/kubernetes/test-infra

**Describe alternatives you've considered**
n/a

**Additional context**
In case our changes are accepted, we don't have to maintain a patch

**Comment by SamoKopecky** [comment]
The changes that we are using right now in the patch file only solve our problem but remove the [admin check](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L235-L243) for other users so we can't offer these changes to upstream.

Changing peribolos for our workflow utilizing already created tokens would be probably unnecessary. What I mean by that is when we supply an argument for a token, peribolos thinks that the token belongs to a user, not an app, which causes problems during the admin check. These problems are:
1. We can't get the app name since peribolos thinks the token belongs to the user and uses an api call only for users (it uses [this](https://docs.github.com/en/rest/users/users#get-the-authenticated-user) instead of [this](https://docs.github.com/en/rest/apps/apps#get-the-authenticated-app)).
2. Even if are able to get the app name the admin check will still fail since the app name is not in the list of admins.

That's why I think the best way forward is to start using the already integrated app authentication peribolos has built-in using a private key and app id parameters (`--github-app-private-key-path` and `--github-app-id`). This would mean peribolos would take care of tokens on its own, separately from the controller.

The dump-config functionality is not working in the current peribolos upstream using app auth but a fix can be implemented to make it work.

So is peribolos app auth something we wanna do, or find a different approach?
/cc @tumido

**Comment by tumido** [comment]
I like the approach of using a native way that is already supported by Peribolos for app integration. I didn't know it existed. I think we should first fix Peribolos upstream to support this auth method for the `dump` action and then we can fully switch over to using the app auth method. :+1:

**Comment by SamoKopecky** [comment]
PR created [here](https://github.com/kubernetes/test-infra/pull/26703)
